- hosts: localhost
  connection: local
  become: true

- name: Cloning Dotfiles repo to dax user
  git:
    repo: https://github.com/Daxtorim/Dotfiles.git
    dest: /home/dax/Dotfiles
    clone: yes
    update: yes
  become_user: dax

- name: Installing dotfiles for dax user
  command:
    cmd: /usr/bin/stow --no-folding --dir=/home/dax/Dotfiles --restow bash zsh vim alacritty
