- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Creating shallow clone of Dotfiles repo for dax user
    git:
      repo: https://github.com/Daxtorim/Dotfiles.git
      dest: /home/dax/Dotfiles
      clone: yes
      depth: 1
      update: yes

  - name: Change ownership of repo to dax user
    file:
      path: /home/dax/Dotfiles
      state: directory
      recurse: yes
      owner: dax
      group: dax

  - name: Get state on .bashrc file
    file:
      path: /home/dax/.bashrc
    register: bash_file
    ignore_errors: yes

  - name: Removing .bashrc file
    when: bash_file["state"] == "file"
    file:
      path: /home/dax/.bashrc
      state: absent
    ignore_errors: yes

  - name: Installing dotfiles for dax user
    command:
      cmd: /usr/bin/stow --no-folding --dir=/home/dax/Dotfiles --restow bash zsh vim
    become_user: dax
