- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Cloning Dotfiles repo to dax user
    git:
      repo: https://github.com/Daxtorim/Dotfiles.git
      dest: /home/dax/Dotfiles
      clone: yes
      update: yes

  - name: Change ownership of repo to dax user
    file:
      path: /home/dax/Dotfiles
      owner: dax
      group: dax
      mode: 0644

  - name: Installing dotfiles for dax user
    command:
      cmd: /usr/bin/stow --no-folding --dir=/home/dax/Dotfiles --restow bash zsh vim alacritty
