#!/bin/sh

### Aliases

# Fancier ls
if [ -x "$(command -v exa)" ]; then
	alias ls='exa --colour=auto --grid'
	alias la='exa --colour=auto --long --group --header --time-style=long-iso --all --all'
else
	alias ls='ls --color=auto'
	alias la='ls --color=auto -lha'
fi

alias grep='grep --color=auto'
alias cgrep="grep -v '^#\|^$' -R"

alias gitgrep="git grep --heading --line-number --column --show-function --break"
alias gitfetch="git fetch --all --tags --force --prune"

# Use correct extraction program based on file extension
extract()
{
	if [ -f "$1" ]; then
		case $1 in
			*.tar.gz) tar xzf "$1" ;;
			*.tar.bz2) tar xjf "$1" ;;
			*.tar) tar xf "$1" ;;
			*.tgz) tar xzf "$1" ;;
			*.tbz2) tar xjf "$1" ;;
			*.gz) gunzip "$1" ;;
			*.bz2) bunzip2 "$1" ;;
			*.rar) unrar x "$1" ;;
			*.zip) unzip "$1" ;;
			*.Z) uncompress "$1" ;;
			*.7z) 7z x "$1" ;;
			*) echo "'$1' cannot be extracted via >extract<" ;;
		esac
	else
		echo "'$1' is not a valid file!"
	fi
}
