#!/bin/sh

export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"

# Check for available editor
if [ -x "$(command -v lvim)" ];then
	# LunarVim
	export EDITOR='lvim'
	export VISUAL='lvim'
elif [ -x "$(command -v vim)" ];then
	export EDITOR='vim'
	export VISUAL='vim'
fi


# Check for avaliable manpager
if [ -x "$(command -v vim)" ];then
	export MANPAGER='vim -c "%! col -b" -c "setlocal ft=man nomod nolist norelativenumber" -c "nmap q :q!" -'
fi


# Install new npm packages globally *for the user* so it won't need `sudo'
export npm_config_prefix="$HOME/.local"


# !!! manually copied over since conda doesn't respect $ZDOTDIR for zsh support !!!
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/dax/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/dax/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/dax/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/dax/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
