#!/bin/sh

alias ga="git add"
alias gaa="git add *"
alias gc="git commit"
alias gco="git checkout"
alias gd="git diff"
alias gds="git diff --staged"
alias gf="git fetch --all --tags --force --prune"
alias gg="git grep --heading --line-number --column --show-function --break"
alias gl="git log"
alias glo="git log --oneline --graph"
alias gp="git push"
alias gr="git restore"
alias grs="git restore --staged"
alias gra="git restore --staged ."
alias gs="git status"

alias grep="grep --color=auto"
alias ip="ip --color=auto"

alias ls="ls --color=auto --group-directories-first"
alias ll="ls --color=auto --group-directories-first --time-style=long-iso -lh"
alias la="ls --color=auto --group-directories-first --time-style=long-iso -lhA"
if [ -x "$(command -v exa)" ]; then
	alias ls="exa --colour=auto --group-directories-first --icons --grid"
	alias ll="exa --colour=auto --group-directories-first --icons --long --group --header --time-style=long-iso"
	alias la="exa --colour=auto --group-directories-first --icons --long --group --header --time-style=long-iso --all"
fi

if [ ! -f "/run/.containerenv" ] \
	&& [ -x "$(command -v toolbox)" ] \
	&& toolbox list --containers | awk '{print $2}' | grep -q "^Std$"
then
	# shellcheck disable=2139
	alias lvim="toolbox run --container Std ${HOME}/.local/bin/lvim"
fi

# Use correct extraction program based on file extension
extract() {
	if [ -f "$1" ]; then
		case $1 in
			*.tar.gz) tar xzf "$1" ;;
			*.tar.bz2) tar xjf "$1" ;;
			*.tar) tar xf "$1" ;;
			*.tgz) tar xzf "$1" ;;
			*.tbz2) tar xjf "$1" ;;
			*.gz) gunzip "$1" ;;
			*.bz2) bunzip2 "$1" ;;
			*.rar) unrar x "$1" ;;
			*.zip) unzip "$1" ;;
			*.Z) uncompress "$1" ;;
			*.7z) 7z x "$1" ;;
			*) echo "»$1« cannot be extracted via »extract«" ;;
		esac
	else
		echo "»$1« is not a valid file!"
	fi
}
