#!/bin/sh

export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"


# Check for available editor
if [ -x "$(command -v lvim)" ];then
	# LunarVim
	export EDITOR='lvim'
	export VISUAL='lvim'
elif [ -x "$(command -v vim)" ];then
	export EDITOR='vim'
	export VISUAL='vim'
fi


# Check for avaliable manpager
if [ -x "$(command -v vim)" ];then
	export MANPAGER='vim -c "%! col -b" -c "setlocal ft=man nomod nolist norelativenumber" -c "nmap q :q!" -'
fi


# Install new npm packages globally *for the user* so it won't need `sudo'
export npm_config_prefix="$HOME/.local"

